project:
  type: website
  output-dir: docs

website:
  title: "Megan Kingsley"
  navbar:
    background: primary
    search: true
    left:
      - href: index.qmd
        text: " "
        icon: house-door-fill
      - href: Job History.qmd
        text: Job History
      - href: Relevant Courses.qmd
      - text: Relevant Courses
        
     
format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true



