project:
  type: website
  output-dir: docs

website:
  title: "Megan Kingsley"
  search: true
  navbar:
    background: light
    left:
      - icon: house-fill
        href: index.qmd
        text: " "
      - text: "Job History"
        href: Job History.qmd
      - text: "Relevant Courses"
        href: Relevant Courses.qmd
      - text: "Projects"
        href: Projects.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
