project:
  type: website
  output-dir: docs

website:
  title: "Megan Kingsley"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: Job History.qmd
        text: Job History
        
     
format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true



